apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - nfs-storage.yaml
  - minio.yaml
  - velero-helm.yaml
  - backup-schedule.yaml
  - etcd-snapshot.yaml
  - velero-cleanup-cronjob.yaml
