---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rancher-values
  namespace: cattle-system
spec:
  encryptedData:
    values.yaml: AgCus0L2SAgaTlXMSBg1rWtsx9zOE+I7CaW9HlPk1boCrWtJgWYlJbXuaojIbY9q6E6G0ouv6mIwmQ6WeHImPO2CBet9JgnTFzb5T0oouMooQ15QpJ25XTvmeF2GwhFSXgQhkJv+czgak1LhLGuw73sTPPyvf1f3SmiunmtcwsKXNPtaXTe3DP7UUovdkFKsIcJBNN0DAF0f1Hl86IN3sJobFurzaUSWoPiM5G6lm0uD9BhSdzle4sNNTFAWzr3ZU8Kqda4TCUm79NdzNTGDVhgULt9Jd6KkKdjpTSYADMBhQ2t+w0c0/anZChI8b5+8PnujzOBxUrgxZ8p2Oj0O0bjEA6iz7li/ybDu7vIko3LLchf4/4J4nlKXRuf4CDJY2uKmjXuJiN49g6WvoMwDCv0ni0DDdFYNUP8hmYkbw84zWtk7R49eLe/1wfJz0uoGOaIgGRnLt9crRHgfu0nHVIK4pxyxqBafoiwpFSjUFRySu+WOev4va5BkfAsxDprWSsEdkoMzFtgbgRt6R/ZMwjrZtqQxDe66ErP309Z+Piz9GzDgl+q+E9ZWwf41EWVmJbtBXBBWwMqxDEO/HY7UQ+R1Vq7CRU8/YY0qyGo2fxJsVvM1m55K8cBvwLe75aoX2/xFcWe3nNyKc7H+bvj0k74qj/uTScct3+lO7smKqLTOdR8wBZXdAHFlEQCIBZYAKGHgks7PFBlo/K5lgZ8VAB1mAq9suavDGWJKwH0CQfzn0z6sASInKVBxMg+hys9fPSygwVdQ15wcBh/2zA==
  template:
    metadata:
      name: rancher-values
      namespace: cattle-system
