apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - proxmox-exporter.yaml
  - proxmox-servicemonitor.yaml
  - ingress-grafana.yaml
  - ingress-grafana-local.yaml
  - dashboards/
